[package]
name = "excel-to-parquet"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "*"
parquet = "*"
arrow = "*"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }

[profile.release]
opt-level = 's'
strip = "debuginfo"
lto = true